name: panda_union
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  provider: ^6.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter_spinkit: ^5.2.0

  shared_preferences: ^2.3.5
  flutter_secure_storage: ^9.2.4

  dropdown_search: ^6.0.1
  webview_flutter: ^4.10.0
  #get: ^4.7.2
  flutter_keyboard_visibility: ^6.0.0

  connectivity_plus: ^6.1.3

  fluttertoast: ^8.2.12
  #overlay_support: ^2.1.0

  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
  
  fonts:
    - family: IconFont
      fonts:
        - asset: fonts/iconfont.ttf
